require('cypress-iframe');
import { faker } from '@faker-js/faker'
let nameFaker = faker.hacker.adjective()
let nameCurso = faker.lorem.words(2)
let Empresa = faker.lorem.words(1)

Cypress.Commands.add('gui_login', ( //Login
    user = 'william.pereira@multti.com',
    password = "123456",
) => {
    cy.visit('/')
    cy.get('#button-login > span').click()
    cy.get(":nth-child(1) > .styles__Container-sc-oo03vd-0").type(user)
    cy.get(":nth-child(2) > .styles__Container-sc-oo03vd-0").type(password, { log: false })
    cy.intercept('POST', 'https://api-ls.homolog.dev.br/api/login').as('request')
    cy.get('.styles__Button-sc-3uo2vx-17').click()
    cy.wait('@request')
    cy.get('@request').its('response.status').should('eq', undefined )
})
Cypress.Commands.add('sessionLogin', (user = 'william.pereira@multti.com', password = "123456") => {
    const login = () => cy.gui_login(user, password);
  
    cy.session({
      user: user,
      cacheSession: true // Adicionando opção de cache
    }, login);
  });
Cypress.Commands.add("logoff", () => { //Saindo da plataforma
    cy.visit('/')
    cy.get('.styles__MenuGroup-sc-hhvtns-6 > .IconAcessar > span').click()
    cy.get('span[class="user-status"]').click().should('be.visible')
    cy.get('span[class="align-middle"]').last().click()
    cy.url().should('eq', 'https://site-ls.homolog.dev.br/')
})
Cypress.Commands.add('exitPlatform', () =>{ //Deslogando da plataforma
    cy.visit('/')
    cy.get('[class="dd-header"]').click()
    cy.get('[class="dd-list-item dd-list-item-1"]').click()
})
Cypress.Commands.add("registerUser", () => { //Cadastrando o Usuário
    cy.get('#button-login > span').click()
    cy.get('span[class="styles__ButtonAccept-sc-p4ahv5-7 Cuhmt"]').click()
    cy.get('.styles__SignUp-sc-3uo2vx-18 > a').click()
    cy.get('.styles__Form-sc-3uo2vx-13 > :nth-child(1) > .styles__Container-sc-oo03vd-0').type('William teste')
    cy.get('input[name="email"]').type('williameste@gmail.com', { log: false })
    cy.get('input[name="phone"]').type('15997845516')
    cy.get('input[name="password"]').type('123456', { log: false })
    cy.get('input[name="privacy"]').click()
    cy.get('.styles__Button-sc-3uo2vx-17').click()
    cy.get(':nth-child(4) > .styles__ButtonOutline-sc-3uo2vx-16').click()
    cy.contains('Confirme o código enviado').should('be.visible')
})
Cypress.Commands.add("addCart", () => { //Adicionando produdo ao carinho
    cy.visit('/')
    cy.get('button[class="styles__Container-sc-1equtqg-0 jprUHo"]').last().click({ scrollBehavior: 'center' })
    cy.get('.styles__ButtonAccept-sc-p4ahv5-7').click()
    //cy.get('[aria-label="Carrinho"]').click()
    cy.visit('/carrinho')
    //cy.reload()
    cy.reload()
    cy.wait(4000)
    cy.iframe('iframe[title="iframe"]').contains('Avançar').click({force:true})
    cy.iframe('iframe[title="iframe"]').contains('Rua José Antônio Ferreira - CEARÁ').click()
    cy.iframe('iframe[title="iframe"]').find('[class="btn btn-primary-default"]').first().click({force:true})
    /*cy.iframe('iframe[title="iframe"]').contains('button', 'Adicionar endereço').click()
    cy.iframe('iframe[title="iframe"]').find('input[name="newAddress.zip_code"]').type('62322765')
    cy.iframe('iframe[title="iframe"]').find('input[name="newAddress.number"]').type('62')
    cy.iframe('iframe[title="iframe"]').contains('button', 'Adicionar').click()
    cy.iframe('iframe[title="iframe"]').contains('Rua José Antônio Ferreira - CEARÁ').click({ scrollBehavior: 'center' })*/
    cy.iframe('iframe[title="iframe"]').contains('Opções de pagamento').should('be.visible')
})
Cypress.Commands.add('paymentCreditCard', ()=>{ //Pagamento Catrtão de crédito
    cy.addCart()
    cy.iframe('iframe[title="iframe"]').find('div[class="vGZvL8c6eNexeJiWr4wVOg== vrH1CI0k2dsWvyNa0+x3RA=="]').click()
    //cy.iframe('iframe[title="iframe"]').find('input[name="newCard.cpf"]').type('418.364.540-90')
    cy.iframe('iframe[title="iframe"]').find('input[name="newCard.name"]').type('Teste automatizado')
    cy.iframe('iframe[title="iframe"]').find('input[name="newCard.number"]').type('4000 0000 0000 0010')
    cy.iframe('iframe[title="iframe"]').find('input[name="newCard.cvv"]').type('123')
    cy.iframe('iframe[title="iframe"]').find('input[name="newCard.valid"]').type('1223')
    cy.iframe('iframe[title="iframe"]').contains('Confirmar Pagamento').click()
    cy.iframe('iframe[title="iframe"]').type('[type="button"]').last().click()
    cy.iframe('iframe[title="iframe"]').contains('Pagamento realizado com sucesso').should('be.visible')
})
Cypress.Commands.add('paymentSlip', () => { //Pagamento no boleto
    cy.addCart()
    cy.iframe('iframe[title="iframe"]').contains('Boleto Bancário').click()
    cy.iframe('iframe[title="iframe"]').contains('Confirmar Emissão').click()
    cy.iframe('iframe[title="iframe"]').contains('Emitir boleto').should('be.visible')
})
Cypress.Commands.add('paymentPix', () => { //Pagamento via Pix
    cy.addCart()
    cy.iframe('iframe[title="iframe"]').contains('PIX').click()
    cy.iframe('iframe[title="iframe"]').contains('Confirmar Pagamento').click()
    cy.iframe('iframe[title="iframe"]').contains('Aguardando confirmação do PIX...').should('be.visible')
})
Cypress.Commands.add('paymentTed', () => { //Pagamento via transferência
    cy.addCart()
    cy.iframe('iframe[title="iframe"]').contains('TED/DOC').click()
    cy.iframe('iframe[title="iframe"]').contains('Confirmar Pagamento').click()
    cy.iframe('iframe[title="iframe"]').contains('Falta só mais um pouco!').should('be.visible')
})
Cypress.Commands.add("registerAddress", () => { //Adicionar endereço na compra
    cy.iframe('iframe[title="iframe"]').contains('button', 'Adicionar endereço').click()
    cy.iframe('iframe[title="iframe"]').find('input[name="newAddress.zip_code"]').type('62322765')
    cy.iframe('iframe[title="iframe"]').find('input[name="newAddress.number"]').type('62')
    cy.iframe('iframe[title="iframe"]').contains('button', 'Adicionar').click()
    cy.contains('Rua José Antônio Ferreira').should('exist')
})
Cypress.Commands.add("checkSideMenu", () => { //Verificão de menus
    cy.visit('/')
    cy.get('[class="styles__ButtonAccept-sc-p4ahv5-7 Cuhmt"]').click()
    cy.get('.styles__MenuGroup-sc-hhvtns-6 > .IconAcessar > span').click()
    cy.get('[class="efeNsGhYhSQNju2yjo1voQ=="').click()
    cy.contains('Administrativo')
    cy.reload()
    cy.contains(`a`, `Feed`).click()
    cy.get('textarea.form-control').first().type('ok')
    cy.get('button[class="btn btn-secondary-gradient"]').first().click()
    cy.contains('Publicação cadastrada com sucesso!').should('be.visible')
    cy.contains(`span`, `Transmissões`).click()
    cy.url().should('eq', 'https://app-ls.homolog.dev.br/cliente/lives')
    cy.contains('div', 'Sala de Análise').click().should('be.visible')
    cy.contains(`span`, `Meus Cursos`).click()
    cy.url().should('eq', 'https://app-ls.homolog.dev.br/cliente/cursos')
    cy.contains(`span`, `Meus E-books`).click()
    cy.url().should('eq', 'https://app-ls.homolog.dev.br/cliente/ebooks')
    cy.contains(`h1`, `Últimos Comprados`).click()
    cy.contains(`a`, `LS Play`).click()
    cy.url().should('eq', 'https://app-ls.homolog.dev.br/cliente/ls-play')
    cy.contains(`span`, `Recomendações`).click()
    cy.url().should('eq', 'https://app-ls.homolog.dev.br/cliente/recomendacoes')
})
Cypress.Commands.add('loginApi', () => { //Logar via API
    cy.request({
        method: 'POST',
        url: 'https://api-ls.homolog.dev.br/api/login',
        body: {
            email: 'william.pereira@multti.com',
            password: 'zaq12wsx',
            initialize_with_readme: true
        }
    }).then((response) => {
        expect(response.status).to.eq(200)
        //expect(response.body).to.have.property('token')
    })
})
Cypress.Commands.add('pathRegistration', () => { //Caminho para ir até cadastro
    cy.visit('/')
    cy.get('.styles__MenuGroup-sc-hhvtns-6 > .IconAcessar > span').click()
    cy.contains('L&S')
    //cy.get('[class="efeNsGhYhSQNju2yjo1voQ=="]').click()
})
Cypress.Commands.add('bookRegistration', () => { //Cadastro de Livros
    const upload = ('image.jpg')
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/livros')
    cy.get('[class="btn btn-primary-default"]').first().should('be.visible').click()
    cy.get('[name="name"]').type(nameFaker).should('be.visible')
    cy.get('[type="checkbox"]').check('0',{force: true}) 
    cy.get('#company_id').select('L&S Educação')
    cy.get('[name="author"]').type('William De Souza')
    cy.get('[data-contents="true"]').first().type(nameFaker)
    cy.contains('Avançar').click()
    cy.get('[data-contents="true"]').last().type('Teste automatizado')
    cy.get('[name="total_pages"]').type('15')
    cy.get('[name="release_year"]').type('2023') 
    cy.get('[name="stock"]').type('20')  
    cy.get('[name="price"]').type('2550')  
    cy.get('[name="eduzz_code"]').type('02')  
    cy.get('[class="RMnN7fG1jHMsJw+kXvO6+w== "]').eq(0).selectFile(upload, { action: ('drag-drop') })
    cy.get('[class="RMnN7fG1jHMsJw+kXvO6+w== "]').eq(1).selectFile(upload, { action: ('drag-drop') })
    cy.intercept('POST', '/api/create-book').as('request')
    cy.contains('Salvar').click()
    cy.wait('@request')
    cy.get('@request').its('response.statusCode').should('eq', 200)
})
Cypress.Commands.add('deleteEbook', () =>{ //Excluir ebook
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/livros')
    cy.get('.btn-outline-secondary > svg').click()
    cy.get('[placeholder="Digite o que deseja buscar"]').type(nameFaker)
    cy.get('span svg[width="15"]').eq(0).click()
    cy.contains('Excluir').click()
    cy.get('[class="btn btn-danger"]').click()
    cy.contains('Livro removido com sucesso!').should('be.visible')
})
Cypress.Commands.add('deleteCourse', () => { //Excluir curso
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/cursos')
    cy.get('.btn-outline-secondary > svg').click()
    cy.get('[placeholder="Digite o que deseja buscar"]').click().type(nameCurso)
    cy.get('[class="pr-1"]').eq(0).click()
    cy.contains('Excluir').click()
    cy.get('[class="btn btn-danger"]').click()
    cy.contains('Curso removido com sucesso!').should('be.visible')
})
Cypress.Commands.add('courseRegistration', () => { //Cadastrar curso
    const upload = ('image.jpg')
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/cursos/cadastro')
    cy.get('input[name="name"]').scrollIntoView({ offset: { top: 150, left: 0 } }).type(nameCurso).should('be.visible')
    cy.get('#company_id').select('L&S Educação')
    cy.get('div[class="d-flex align-items-center"]').selectFile(upload, { action: ('drag-drop') })
    cy.get('div[class="RMnN7fG1jHMsJw+kXvO6+w== "]').first().selectFile(upload, { action: ('drag-drop') })
    cy.get('[name="trailer_url"]').type('https://app-hml.libertaplay.com.br/login%27')
    cy.get('div[class="rdw-editor-main"]').first().type(nameFaker)
    cy.get('div[class="rdw-editor-main"]').eq(1).type(nameFaker)
    cy.get('div[class="RMnN7fG1jHMsJw+kXvO6+w== "]').eq(0).selectFile(upload, { action: ('drag-drop') })
    cy.get('div[class="RMnN7fG1jHMsJw+kXvO6+w== "]').eq(1).selectFile(upload, { action: ('drag-drop') })
    cy.get('div[class="RMnN7fG1jHMsJw+kXvO6+w== "]').last().selectFile(upload, { action: ('drag-drop') })
    cy.get('#main-data-button').click().should('have.text', 'Avançar')
})
Cypress.Commands.add('salesSetup', () => { //Configuração de venda
    cy.get('input[class="form-control"]').eq(4).type('20').should('be.visible')
    cy.get('[name="sales_start_date"]').type('19/10/2022').should('be.visible')
    cy.get('input[name="eduzz_cart_url"]').type('/').should('be.visible')
    cy.get('input[name="price_info"]').type('10.00').should('be.visible')
    cy.get('div[class="DraftEditor-root"]').eq(2).type('Teste automatizado').should('be.visible')
    cy.get('[name="access_period_id"]').select('Mensal')
    cy.get('input[name="price"]').type('100').should('be.visible')
    cy.get('button[class="btn btn-secondary"]').first().click()
    cy.get('[type="submit"]').eq(1).click() 
})
Cypress.Commands.add('courseSettings', () => { //Configuração de curso
    cy.get('[name="classes_start_date"]').type('15102023')
    cy.get('[name="total_classes"]').type('1500')
    cy.get('[name="total_hours"]').type('5h')
    cy.get('[class="select__placeholder css-1wa3eu0-placeholder"]').eq(0).click().type('iniciante{enter}')
    cy.get('[name="date"]').last().type('15102023')
    cy.get('[name="hour"]').type('10:00')
    cy.get(':nth-child(3) > .col-md-2 > .btn').click().should('have.text', 'Adicionar')
    cy.get('[name="id"]').first().select('Stormer')
    cy.get('[name="id"]').last().select('adm')
    cy.get('[name="order"]').first().type('5')
    cy.get('[name="order"]').last().type('6')
    cy.get(':nth-child(5) > .col-md-2 > .btn').click().should('have.text', 'Adicionar')
    cy.get(':nth-child(7) > .col-md-2 > .btn').click().should('have.text', 'Adicionar')
    cy.get('#course-settings-button').click().should('have.text', 'Avançar') 
})
Cypress.Commands.add('courseModality', () => { //Configuração modalidade do curso
    cy.get('[name="without_discount"').check({ force: true })
    cy.contains('Sem cupom de desconto').should('be.visible')
    cy.get('[name="pre_sale"]').check({ force: true })
    cy.contains('Pré-Venda').should('be.visible')
    cy.get('[name="online"').check({ force: true })
    cy.contains('Online').should('be.visible')
    cy.get('[name="online_live"').check({ force: true })
    cy.contains('Online ao vivo').should('be.visible')
    cy.get('[class="switch-icon-right"]').eq(1).click({ force: true })
    cy.get('#course-modalities-button').click().should('have.text', 'Avançar')
})
Cypress.Commands.add('courseDisplay', () => { //Configuração exibição de curso
    cy.get('[name="feature.online"').check({ force: true })
    cy.get('[name="feature.level"').check({ force: true })
    cy.get('[name="feature.records_access"').check({ force: true })
    cy.get('[name="feature.total_classes').check({ force: true })
    cy.get('[name="feature.certificate"').check({ force: true })
    cy.get('[name="feature.total_hours"').check({ force: true })
    cy.get('[name="feature.further_material"').check({ force: true })
    cy.get('[name="zip_code"]').type('62322240')
    cy.get('.col-md-4 > :nth-child(1) > .form-group > .form-control').type('100')
    cy.intercept('POST', '/api/create-course').as('request')
    cy.get('[class="btn btn-primary-default"]').eq(5).click()
    cy.wait('@request')
    cy.get('@request').its('response.statusCode').should('eq', 200)
})
Cypress.Commands.add('createCompany', () => { //Cadastrar empresa
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/empresas')
    cy.get('[class="btn btn-primary-default"]').first().should('be.visible').click()
    cy.get('form > .form-group > .form-control').type(Empresa)
    cy.contains('Salvar').click()
    cy.intercept('POST', '/api/create-company').as('request').wait(1000)
    cy.wait('@request')
    cy.get('@request').its('response.statusCode').should('eq', 200)
})
Cypress.Commands.add('deleteCompany',() => {//Deletar empressa
    cy.pathRegistration()
    cy.visit('https://app-ls.homolog.dev.br/empresas')
    cy.get('.btn-outline-secondary > svg').click()
    cy.get('[placeholder="Digite o que deseja buscar"]').type(Empresa)
    cy.get('svg[width="15"').eq(2).click()
    cy.contains('Excluir').click({force:true})
    cy.get('[class="btn btn-danger"').click()
    cy.get('[class="Toastify__toast-body"]').should('have.text', 'Empresa removida com sucesso!')
})